[package]
name = "swimlane-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
swimlane = { path = "../swimlane" }
