name: "Release"

permissions:
  contents: "write"

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  get-tag:
    name: Get Tag From Package Version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.TAG }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get tag
        id: get-tag
        shell: bash
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

  create-release:
    name: Create release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs:
      - get-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Create release"
        uses: "taiki-e/create-gh-release-action@v1"
        with:
          # (optional) Path to changelog.
          # changelog: CHANGELOG.md
          branch: main
          ref: refs/tags/${{ needs.get-tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    name: Upload assets to Github releases
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs:
      - create-release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: swimlane-cli
          ref: refs/tags/${{ needs.get-tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
