name: Continuous integration

on:
  push:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust (Stable)
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - uses: Swatinem/rust-cache@v2
      - run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust (Stable)
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - uses: Swatinem/rust-cache@v2
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust (Stable)
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: rustup component add rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust (Stable)
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy -- -D warnings

  create-release:
    name: Create release
    if: ${{ startsWith(github.ref, 'refs/tags/swimlane-cli') }}
    needs:
      - check
      - test
      - fmt
      - clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set tag
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create release
        uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog.
          # changelog: CHANGELOG.md
          branch: main
          prefix: swimlane-cli@
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    name: Upload assets to Github releases
    if: ${{ startsWith(github.ref, 'refs/tags/swimlane-cli') }}
    needs:
      - create-release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set tag
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: swimlane-cli
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
